id = "claude-code-dark"
name = "Claude Code Dark"
description = "A warm dark theme inspired by Claude and Anthropic's brand colors with semi-transparent backgrounds"
version = "1.0.0"
schema_version = 1
authors = ["Eric Buess <your-email@example.com>"]
repository = "https://github.com/ericbuess/zed-claude-theme"
license = "MIT"

[theme]
path = "themes/"